### ISSUE TITLE
Tried to install on android emulator 

### ISSUE THREAD

**Issue by Nopsled** [HuskyDG/magisk_overlayfs#3]
Im running Android 13 (API 33) rooted with magisk in android emulator (NOT debug).
In magisk when I try to install the .zip of the release (2.3) i get the error: 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/78918436/220480702-2e11a451-3a2a-4958-b871-520295aba57d.png">

**Comment by likkai** [comment]
same issue
