### ISSUE TITLE
On KernelSU, Overlayfs by this module is evaporated?

### ISSUE THREAD

**Issue by h88782481** [HuskyDG/magisk_overlayfs#7]
[overlayfs.log](https://github.com/HuskyDG/magisk_overlayfs/files/11185582/overlayfs.log)

**Comment by h88782481** [comment]
The module installed is the latest version 2.6

**Comment by h88782481** [comment]
> 

mt

**Comment by h88782481** [comment]
> Try this version, modify `mode.sh` and set `OVERLAY_MODE=1` (read-write)

Still read/write failure
![image](https://user-images.githubusercontent.com/54714341/230780637-a35a0b3b-5ef3-478a-80a2-7704305f2caf.png)
![image](https://user-images.githubusercontent.com/54714341/230780664-27b731a8-6f0a-45ab-a88f-44718b10ffd8.png)

**Comment by h88782481** [comment]
> Reboot then?

It still doesn't work.

**Comment by h88782481** [comment]
> use material files instead of MT Manager https://github.com/zhanghai/MaterialFiles

![image](https://user-images.githubusercontent.com/54714341/230781516-2c888964-f156-4ce8-8cec-114dea54bfa5.png)

**Comment by h88782481** [comment]
I'm using kernelSU

**Comment by h88782481** [comment]
> add files to root of `/system`, `/vendor`, ... is not supported only subdirectories such as `/system/bin`, `/system/etc`, ...

![image](https://user-images.githubusercontent.com/54714341/230781781-4ca290c8-253d-45e4-97a5-6c4ba0bc09fb.png)

**Comment by h88782481** [comment]
[overlayfs.log](https://github.com/HuskyDG/magisk_overlayfs/files/11185767/overlayfs.log)

**Comment by h88782481** [comment]
> Turn off all modules except `magisk_overlayfs`

I'll give it a try

**Comment by h88782481** [comment]
> Turn off all modules except `magisk_overlayfs`

![image](https://user-images.githubusercontent.com/54714341/230782250-f11f1709-4957-4390-80ba-fc455304f4c7.png)
![image](https://user-images.githubusercontent.com/54714341/230782262-e934a181-d479-425f-ab29-6555946e8c62.png)
Can't

**Comment by h88782481** [comment]
[output.txt](https://github.com/HuskyDG/magisk_overlayfs/files/11185800/output.txt)

**Comment by h88782481** [comment]
I'm curious, too

**Comment by h88782481** [comment]
![image](https://user-images.githubusercontent.com/54714341/230785204-768c8aa0-ba44-4611-866c-d5b1a3c88ca4.png)
![image](https://user-images.githubusercontent.com/54714341/230785246-3d2cb069-5244-4559-bcaf-00d15d26c23d.png
[overlayfs.log](https://github.com/HuskyDG/magisk_overlayfs/files/11185896/overlayfs.log)
)

**Comment by h88782481** [comment]
I'm going to rest, and the rest of the test may not be done until tomorrow

**Comment by H1mJT** [comment]
![Screenshot_20230409-221833_Material Files](https://user-images.githubusercontent.com/92359223/230785605-3ee4b822-0723-47dc-8216-8a7034952cdc.png)
Adaway successfully updated the host file, so system is rw but material files still shows as read only.

**Comment by H1mJT** [comment]
Okay it is working with [Xplore manager](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore) by selecting root access as superuser + mount writable.

**Comment by h88782481** [comment]
> Okay it is working with [Xplore manager](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore) by selecting root access as superuser + mount writable.

![image](https://user-images.githubusercontent.com/54714341/230808188-44f814f0-db0d-4f5e-b405-6359b15a29f7.png)

**Comment by h88782481** [comment]
My kernelSU version is 10738

**Comment by h88782481** [comment]
> Try kill zygote by `setprop ctl.restart zygote`. After that send `mount` output.



> Try kill zygote by `setprop ctl.restart zygote`. After that send `mount` output.

[out.txt](https://github.com/HuskyDG/magisk_overlayfs/files/11186877/out.txt)
This is the output of the mount after zygote is killed

**Comment by h88782481** [comment]
> The result of this command? `su -c nsenter -t 1 -m mount`
Sorry, su on kernelSU doesn't have the -t parameter

**Comment by h88782481** [comment]
![image](https://user-images.githubusercontent.com/54714341/230809382-0664a436-bd91-4ce4-8002-bcbd2fc89725.png)

**Comment by h88782481** [comment]
> `su -c "nsenter -t 1 -m mount"`
[out.txt](https://github.com/HuskyDG/magisk_overlayfs/files/11186955/out.txt)

**Comment by h88782481** [comment]
Is it because of the kernel? I use a third party kernel

**Comment by h88782481** [comment]
> OverlayFS is unmounted by kernelsu? https://github.com/tiann/KernelSU/blob/main/kernel/core_hook.c

I don't know, the author of ksu originally planned to have the function of mounting system partitions, but it was cancelled for some reason

**Comment by h88782481** [comment]
[KernelSU_bugreport_2023-04-10_10_26.tar.gz](https://github.com/HuskyDG/magisk_overlayfs/files/11187108/KernelSU_bugreport_2023-04-10_10_26.tar.gz)

**Comment by h88782481** [comment]
![image](https://user-images.githubusercontent.com/54714341/230819611-7bc49ebb-cce0-4473-91b6-1c7ace664e45.png)
I think this module will not support ksu for the time being

**Comment by h88782481** [comment]
I think we should first remove the statement that supports ksu

**Comment by h88782481** [comment]
> Try https://github.com/HuskyDG/magisk_overlayfs/actions/runs/4654631831

Do you need to update the kernel?

**Comment by h88782481** [comment]
I'll have a try.

**Comment by h88782481** [comment]
succeeded

**Comment by h88782481** [comment]
Material Files and mt were successful

**Comment by h88782481** [comment]
![image](https://user-images.githubusercontent.com/54714341/230831229-3be94562-1d36-4b1c-a830-0f59980691e7.png)
